services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-app
    ports:
      - "5001:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-please-change}
      - PYTHONUNBUFFERED=1  # ✅ 실시간 로그 출력
    volumes:
      # 개발 시 코드 변경사항 실시간 반영
      - ./app.py:/app/app.py
      - ./services:/app/services
      - ./templates:/app/templates
      - ./static:/app/static
      - ./config:/app/config
      - ./tools:/app/tools
    restart: unless-stopped
    networks:
      - chatbot-network
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

networks:
  chatbot-network:
    driver: bridge